// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wrtroad_infraestructureweb.api.core.infrastructure.data.context;

#nullable disable

namespace wrtroad_infraestructureweb.api.core.infrastructure.data.migrations
{
    [DbContext(typeof(WrtRoadDbContext))]
    partial class WrtRoadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("wrtroad_infraestructureweb.api.core.domain.entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "super-admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "mid-admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "client-writter"
                        });
                });

            modelBuilder.Entity("wrtroad_infraestructureweb.api.core.domain.entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegister")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateRegister = new DateTime(2025, 4, 6, 21, 42, 32, 605, DateTimeKind.Local).AddTicks(7520),
                            Email = "andersonmikol@live.com",
                            Name = "Anderson",
                            Password = "eIN8kyMYRkwfELCca+aSO0hir851wG+c7C/pQ23TX5MrXvy/6QJZF/5Wf9dlB3q0VPgMWL/uYtUiPGqo+v+5YQ==",
                            Salt = "lEX/6gyp11opuxs2nzFk6+opDs/QZ7Mme7/NKpmOGmjZtdmU5i+SIeDFC6WwrvqZMaSQyIzyes4vbUdyrGTDuM8CfXUkd5nhie26pFHjdwIG6ta6aowu65t1UgMyHLBrtynz9zdIBrBLSCwxkBLd5J/bPqxCuFkQGpe8IueimzA=",
                            Surname = "Chanchay",
                            Username = "andersoundz"
                        });
                });

            modelBuilder.Entity("wrtroad_infraestructureweb.api.core.domain.entities.UserRoleEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("wrtroad_infraestructureweb.api.modules.auth.domain.entities.EmailVerificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("wrtroad_infraestructureweb.api.core.domain.entities.UserRoleEntity", b =>
                {
                    b.HasOne("wrtroad_infraestructureweb.api.core.domain.entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wrtroad_infraestructureweb.api.core.domain.entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("wrtroad_infraestructureweb.api.modules.auth.domain.entities.EmailVerificationEntity", b =>
                {
                    b.HasOne("wrtroad_infraestructureweb.api.core.domain.entities.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("wrtroad_infraestructureweb.api.modules.auth.domain.entities.EmailVerificationEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("wrtroad_infraestructureweb.api.core.domain.entities.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("wrtroad_infraestructureweb.api.core.domain.entities.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
